/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CardComponent: typeof import('./src/components/GameArea/CardComponent.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    FooterComponent: typeof import('./src/components/FooterArea/FooterComponent.vue')['default']
    GameComponent: typeof import('./src/components/GameArea/GameComponent.vue')['default']
    HeaderComponent: typeof import('./src/components/HeaderArea/HeaderComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
